apiVersion: v1
kind: Service
metadata:
  name: {{ include "dks-ui.fullname" . }}
  labels:
    {{- include "dks-ui.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: |
    {{- tpl $value $ | nindent 6 }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "dks-ui.selectorLabels" . | nindent 4 }}
