#!/usr/bin/env bash
# start templated
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="${HERE}/../.."
INSTALL_PYTHON=/usr/local/opt/pre-commit/libexec/bin/python3.11
ARGS=(install --config="${ROOT_DIR}/.pre-commit-config.yaml")
# end templated

ARGS+=(-f --install-hooks "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
