name: Build Container Image

on:
  pull_request:
    branches: [ main ]

  workflow_call:
    inputs:
      tagTypes:
        required: false
        type: string
        default: |
          type=sha

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          # when opened on pull request, no inputs are provided. when empty the
          # defaults are used which produces pr-* as the tag to the image using
          # the below information.
          #   type=schedule,pattern=nightly,enable=true,priority=1000
          #   type=ref,event=branch,enable=true,priority=600
          #   type=ref,event=tag,enable=true,priority=600
          #   type=ref,event=pr,prefix=pr-,enable=true,priority=600
          tags: |
            ${{ inputs.tagTypes }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

      - name: Build and push Docker images
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
