# This workflow checks that commits on the PR have been made against the
# conventional commits spec.

name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: liatrio/github-actions/conventional-pr-title@7208146c9ce4749b4ff44ff8030d953a578fa209 # master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
